# Generated by Django 5.1.1 on 2024-10-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('fresh', 'Fresh'), ('on_sale', 'On Sale'), ('organic', 'Organic'), ('best_seller', 'Best Seller')], max_length=255, null=True),
        ),
    ]
