# Generated by Django 5.1.1 on 2024-10-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('Fresh', 'fresh'), ('On Sale', 'on_sale'), ('Organic', 'organic'), ('Best Seller', 'best_seller')], max_length=255, null=True),
        ),
    ]
