# Generated by Django 5.1.1 on 2024-10-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cartitem'),
        ('store', '0006_alter_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='cart',
            field=models.ManyToManyField(through='order.CartItem', to='store.product'),
        ),
    ]
